version: '3.8'

networks:
  dockerapi-dev:
    driver: bridge

services:
  api:
    image: api:latest
    container_name: "API"
    depends_on:
      - postgres_image
      - rabbit_mq_image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - documentsImageVolume:/app/data
    environment:
      DB_CONNECTION_STRING: "Host=postgres_image;Port=5432;Database=postgres;User ID=admti;Password=ABcX6ZfjT9p4qrS7vgNhM2sPD8xLR5JEF3QT"
    networks:
      - dockerapi-dev
  
  postgres_image:
    image: postgres:latest
    container_name: "PostgreSQL"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "admti"
      POSTGRES_PASSWORD: "ABcX6ZfjT9p4qrS7vgNhM2sPD8xLR5JEF3QT"
      POSTGRES_DB: "postgres"
    networks:
      - dockerapi-dev
  
  rabbit_mq_image:
    image: "rabbitmq:3.13-management"
    container_name: "RabbitMQ"
    ports:
      - "8082:15672"
      - "5672:5672"
    restart: always
    networks:
      - dockerapi-dev

volumes:
  db_volume:
  documentsImageVolume: